pid:
  kp: 0.5
  ki: 0.00
  kd: 0.00
pure_pursuit:
  mode: fixed  # 1) [fixed] lookahead distance 2) [variable] k_pre * v
  lookahead_distance: 4.0 # [m]
  k_pre: 1.5
control_switch:
  longitudinal: true # Start: true; Shutdown: false
  lateral: true
longitudinal_mode: 1 # 1: constant speed 2: planned speed 3: desired distance
desired_speed: 0.5 # [-1,1]
desired_distance: 5 # m
