// Generated by gencpp from file common_msgs/ChassisState.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_CHASSISSTATE_H
#define COMMON_MSGS_MESSAGE_CHASSISSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace common_msgs
{
template <class ContainerAllocator>
struct ChassisState_
{
  typedef ChassisState_<ContainerAllocator> Type;

  ChassisState_()
    : header()
    , real_acc_pedal(0)
    , real_brake_pedal(0)
    , real_steer_angle_left(0.0)
    , real_steer_angle_right(0.0)
    , vehicle_lon_acceleration(0.0)  {
    }
  ChassisState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , real_acc_pedal(0)
    , real_brake_pedal(0)
    , real_steer_angle_left(0.0)
    , real_steer_angle_right(0.0)
    , vehicle_lon_acceleration(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _real_acc_pedal_type;
  _real_acc_pedal_type real_acc_pedal;

   typedef uint8_t _real_brake_pedal_type;
  _real_brake_pedal_type real_brake_pedal;

   typedef double _real_steer_angle_left_type;
  _real_steer_angle_left_type real_steer_angle_left;

   typedef double _real_steer_angle_right_type;
  _real_steer_angle_right_type real_steer_angle_right;

   typedef double _vehicle_lon_acceleration_type;
  _vehicle_lon_acceleration_type vehicle_lon_acceleration;





  typedef boost::shared_ptr< ::common_msgs::ChassisState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::ChassisState_<ContainerAllocator> const> ConstPtr;

}; // struct ChassisState_

typedef ::common_msgs::ChassisState_<std::allocator<void> > ChassisState;

typedef boost::shared_ptr< ::common_msgs::ChassisState > ChassisStatePtr;
typedef boost::shared_ptr< ::common_msgs::ChassisState const> ChassisStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::ChassisState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::ChassisState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_msgs::ChassisState_<ContainerAllocator1> & lhs, const ::common_msgs::ChassisState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.real_acc_pedal == rhs.real_acc_pedal &&
    lhs.real_brake_pedal == rhs.real_brake_pedal &&
    lhs.real_steer_angle_left == rhs.real_steer_angle_left &&
    lhs.real_steer_angle_right == rhs.real_steer_angle_right &&
    lhs.vehicle_lon_acceleration == rhs.vehicle_lon_acceleration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_msgs::ChassisState_<ContainerAllocator1> & lhs, const ::common_msgs::ChassisState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::ChassisState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::ChassisState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::ChassisState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::ChassisState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::ChassisState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::ChassisState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::ChassisState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "250f4d938e1a97be304a5f49b807d794";
  }

  static const char* value(const ::common_msgs::ChassisState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x250f4d938e1a97beULL;
  static const uint64_t static_value2 = 0x304a5f49b807d794ULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::ChassisState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/ChassisState";
  }

  static const char* value(const ::common_msgs::ChassisState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::ChassisState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# real acc pedal value\n"
"uint8 real_acc_pedal\n"
"\n"
"# real brake pedal value\n"
"uint8 real_brake_pedal\n"
"\n"
"# real steering wheel angle\n"
"float64 real_steer_angle_left\n"
"float64 real_steer_angle_right\n"
"\n"
"# vehicle longitudinal acceleration\n"
"float64 vehicle_lon_acceleration\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::common_msgs::ChassisState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::ChassisState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.real_acc_pedal);
      stream.next(m.real_brake_pedal);
      stream.next(m.real_steer_angle_left);
      stream.next(m.real_steer_angle_right);
      stream.next(m.vehicle_lon_acceleration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChassisState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::ChassisState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::ChassisState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "real_acc_pedal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.real_acc_pedal);
    s << indent << "real_brake_pedal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.real_brake_pedal);
    s << indent << "real_steer_angle_left: ";
    Printer<double>::stream(s, indent + "  ", v.real_steer_angle_left);
    s << indent << "real_steer_angle_right: ";
    Printer<double>::stream(s, indent + "  ", v.real_steer_angle_right);
    s << indent << "vehicle_lon_acceleration: ";
    Printer<double>::stream(s, indent + "  ", v.vehicle_lon_acceleration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_CHASSISSTATE_H
