// Generated by gencpp from file common_msgs/ControlState.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_CONTROLSTATE_H
#define COMMON_MSGS_MESSAGE_CONTROLSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace common_msgs
{
template <class ContainerAllocator>
struct ControlState_
{
  typedef ControlState_<ContainerAllocator> Type;

  ControlState_()
    : header()
    , lateral_error(0.0)
    , heading_error(0.0)
    , dot_lateral_error(0.0)
    , dot_heading_error(0.0)  {
    }
  ControlState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lateral_error(0.0)
    , heading_error(0.0)
    , dot_lateral_error(0.0)
    , dot_heading_error(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _lateral_error_type;
  _lateral_error_type lateral_error;

   typedef double _heading_error_type;
  _heading_error_type heading_error;

   typedef double _dot_lateral_error_type;
  _dot_lateral_error_type dot_lateral_error;

   typedef double _dot_heading_error_type;
  _dot_heading_error_type dot_heading_error;





  typedef boost::shared_ptr< ::common_msgs::ControlState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::ControlState_<ContainerAllocator> const> ConstPtr;

}; // struct ControlState_

typedef ::common_msgs::ControlState_<std::allocator<void> > ControlState;

typedef boost::shared_ptr< ::common_msgs::ControlState > ControlStatePtr;
typedef boost::shared_ptr< ::common_msgs::ControlState const> ControlStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::ControlState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::ControlState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_msgs::ControlState_<ContainerAllocator1> & lhs, const ::common_msgs::ControlState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lateral_error == rhs.lateral_error &&
    lhs.heading_error == rhs.heading_error &&
    lhs.dot_lateral_error == rhs.dot_lateral_error &&
    lhs.dot_heading_error == rhs.dot_heading_error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_msgs::ControlState_<ContainerAllocator1> & lhs, const ::common_msgs::ControlState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::ControlState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::ControlState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::ControlState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::ControlState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::ControlState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::ControlState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::ControlState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "482c5c5ba4aa1b0cca755e883ff62627";
  }

  static const char* value(const ::common_msgs::ControlState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x482c5c5ba4aa1b0cULL;
  static const uint64_t static_value2 = 0xca755e883ff62627ULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::ControlState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/ControlState";
  }

  static const char* value(const ::common_msgs::ControlState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::ControlState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# lateral error \n"
"float64 lateral_error\n"
"\n"
"# heading error\n"
"float64 heading_error\n"
"\n"
"# dot lateral error\n"
"float64 dot_lateral_error\n"
"\n"
"# dot heading error\n"
"float64 dot_heading_error\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::common_msgs::ControlState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::ControlState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lateral_error);
      stream.next(m.heading_error);
      stream.next(m.dot_lateral_error);
      stream.next(m.dot_heading_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::ControlState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::ControlState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lateral_error: ";
    Printer<double>::stream(s, indent + "  ", v.lateral_error);
    s << indent << "heading_error: ";
    Printer<double>::stream(s, indent + "  ", v.heading_error);
    s << indent << "dot_lateral_error: ";
    Printer<double>::stream(s, indent + "  ", v.dot_lateral_error);
    s << indent << "dot_heading_error: ";
    Printer<double>::stream(s, indent + "  ", v.dot_heading_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_CONTROLSTATE_H
