// Generated by gencpp from file common_msgs/ControlCommand.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_CONTROLCOMMAND_H
#define COMMON_MSGS_MESSAGE_CONTROLCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common_msgs
{
template <class ContainerAllocator>
struct ControlCommand_
{
  typedef ControlCommand_<ContainerAllocator> Type;

  ControlCommand_()
    : control_mode(0)
    , linear_velocity(0.0)
    , linear_acceleration(0.0)
    , steering_angle(0.0)  {
    }
  ControlCommand_(const ContainerAllocator& _alloc)
    : control_mode(0)
    , linear_velocity(0.0)
    , linear_acceleration(0.0)
    , steering_angle(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _control_mode_type;
  _control_mode_type control_mode;

   typedef double _linear_velocity_type;
  _linear_velocity_type linear_velocity;

   typedef double _linear_acceleration_type;
  _linear_acceleration_type linear_acceleration;

   typedef double _steering_angle_type;
  _steering_angle_type steering_angle;





  typedef boost::shared_ptr< ::common_msgs::ControlCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::ControlCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ControlCommand_

typedef ::common_msgs::ControlCommand_<std::allocator<void> > ControlCommand;

typedef boost::shared_ptr< ::common_msgs::ControlCommand > ControlCommandPtr;
typedef boost::shared_ptr< ::common_msgs::ControlCommand const> ControlCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::ControlCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::ControlCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_msgs::ControlCommand_<ContainerAllocator1> & lhs, const ::common_msgs::ControlCommand_<ContainerAllocator2> & rhs)
{
  return lhs.control_mode == rhs.control_mode &&
    lhs.linear_velocity == rhs.linear_velocity &&
    lhs.linear_acceleration == rhs.linear_acceleration &&
    lhs.steering_angle == rhs.steering_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_msgs::ControlCommand_<ContainerAllocator1> & lhs, const ::common_msgs::ControlCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::ControlCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::ControlCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::ControlCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::ControlCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::ControlCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::ControlCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7948587a63d4431bb0f466a6afd13b2c";
  }

  static const char* value(const ::common_msgs::ControlCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7948587a63d4431bULL;
  static const uint64_t static_value2 = 0xb0f466a6afd13b2cULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/ControlCommand";
  }

  static const char* value(const ::common_msgs::ControlCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 control_mode   # 1 for manual control\n"
"float64 linear_velocity\n"
"float64 linear_acceleration #m/s^2\n"
"float64 steering_angle\n"
;
  }

  static const char* value(const ::common_msgs::ControlCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::ControlCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control_mode);
      stream.next(m.linear_velocity);
      stream.next(m.linear_acceleration);
      stream.next(m.steering_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::ControlCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::ControlCommand_<ContainerAllocator>& v)
  {
    s << indent << "control_mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.control_mode);
    s << indent << "linear_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.linear_velocity);
    s << indent << "linear_acceleration: ";
    Printer<double>::stream(s, indent + "  ", v.linear_acceleration);
    s << indent << "steering_angle: ";
    Printer<double>::stream(s, indent + "  ", v.steering_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_CONTROLCOMMAND_H
