// Generated by gencpp from file common_msgs/MagneticSignal.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_MAGNETICSIGNAL_H
#define COMMON_MSGS_MESSAGE_MAGNETICSIGNAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace common_msgs
{
template <class ContainerAllocator>
struct MagneticSignal_
{
  typedef MagneticSignal_<ContainerAllocator> Type;

  MagneticSignal_()
    : header()
    , intensity(0)
    , current_loc(0)
    , middle_loc(0)  {
    }
  MagneticSignal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , intensity(0)
    , current_loc(0)
    , middle_loc(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _intensity_type;
  _intensity_type intensity;

   typedef int32_t _current_loc_type;
  _current_loc_type current_loc;

   typedef int32_t _middle_loc_type;
  _middle_loc_type middle_loc;





  typedef boost::shared_ptr< ::common_msgs::MagneticSignal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::MagneticSignal_<ContainerAllocator> const> ConstPtr;

}; // struct MagneticSignal_

typedef ::common_msgs::MagneticSignal_<std::allocator<void> > MagneticSignal;

typedef boost::shared_ptr< ::common_msgs::MagneticSignal > MagneticSignalPtr;
typedef boost::shared_ptr< ::common_msgs::MagneticSignal const> MagneticSignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::MagneticSignal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::MagneticSignal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_msgs::MagneticSignal_<ContainerAllocator1> & lhs, const ::common_msgs::MagneticSignal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.intensity == rhs.intensity &&
    lhs.current_loc == rhs.current_loc &&
    lhs.middle_loc == rhs.middle_loc;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_msgs::MagneticSignal_<ContainerAllocator1> & lhs, const ::common_msgs::MagneticSignal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::MagneticSignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::MagneticSignal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::MagneticSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::MagneticSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::MagneticSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::MagneticSignal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::MagneticSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ef1a2bcbce072ce84a5a2982b030642";
  }

  static const char* value(const ::common_msgs::MagneticSignal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ef1a2bcbce072ceULL;
  static const uint64_t static_value2 = 0x84a5a2982b030642ULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::MagneticSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/MagneticSignal";
  }

  static const char* value(const ::common_msgs::MagneticSignal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::MagneticSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"int32 intensity\n"
"int32 current_loc\n"
"int32 middle_loc\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::common_msgs::MagneticSignal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::MagneticSignal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.intensity);
      stream.next(m.current_loc);
      stream.next(m.middle_loc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MagneticSignal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::MagneticSignal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::MagneticSignal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "intensity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.intensity);
    s << indent << "current_loc: ";
    Printer<int32_t>::stream(s, indent + "  ", v.current_loc);
    s << indent << "middle_loc: ";
    Printer<int32_t>::stream(s, indent + "  ", v.middle_loc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_MAGNETICSIGNAL_H
