// Generated by gencpp from file common_msgs/RemoteControl.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_REMOTECONTROL_H
#define COMMON_MSGS_MESSAGE_REMOTECONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace common_msgs
{
template <class ContainerAllocator>
struct RemoteControl_
{
  typedef RemoteControl_<ContainerAllocator> Type;

  RemoteControl_()
    : header()
    , mode(0)
    , accel(0.0)
    , steer(0.0)  {
    }
  RemoteControl_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mode(0)
    , accel(0.0)
    , steer(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _mode_type;
  _mode_type mode;

   typedef float _accel_type;
  _accel_type accel;

   typedef float _steer_type;
  _steer_type steer;





  typedef boost::shared_ptr< ::common_msgs::RemoteControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::RemoteControl_<ContainerAllocator> const> ConstPtr;

}; // struct RemoteControl_

typedef ::common_msgs::RemoteControl_<std::allocator<void> > RemoteControl;

typedef boost::shared_ptr< ::common_msgs::RemoteControl > RemoteControlPtr;
typedef boost::shared_ptr< ::common_msgs::RemoteControl const> RemoteControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::RemoteControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::RemoteControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_msgs::RemoteControl_<ContainerAllocator1> & lhs, const ::common_msgs::RemoteControl_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.mode == rhs.mode &&
    lhs.accel == rhs.accel &&
    lhs.steer == rhs.steer;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_msgs::RemoteControl_<ContainerAllocator1> & lhs, const ::common_msgs::RemoteControl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::RemoteControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::RemoteControl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::RemoteControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::RemoteControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::RemoteControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::RemoteControl_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::RemoteControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f4f51bd3e431e8821d9e9c70319162b";
  }

  static const char* value(const ::common_msgs::RemoteControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f4f51bd3e431e88ULL;
  static const uint64_t static_value2 = 0x21d9e9c70319162bULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::RemoteControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/RemoteControl";
  }

  static const char* value(const ::common_msgs::RemoteControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::RemoteControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"int8 mode\n"
"float32 accel #[-1.0,1.0]\n"
"float32 steer #[-1.0,1.0]\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::common_msgs::RemoteControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::RemoteControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mode);
      stream.next(m.accel);
      stream.next(m.steer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RemoteControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::RemoteControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::RemoteControl_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "accel: ";
    Printer<float>::stream(s, indent + "  ", v.accel);
    s << indent << "steer: ";
    Printer<float>::stream(s, indent + "  ", v.steer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_REMOTECONTROL_H
