// Generated by gencpp from file common_msgs/SerialMsg.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_SERIALMSG_H
#define COMMON_MSGS_MESSAGE_SERIALMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace common_msgs
{
template <class ContainerAllocator>
struct SerialMsg_
{
  typedef SerialMsg_<ContainerAllocator> Type;

  SerialMsg_()
    : header()
    , data()
    , length(0)  {
      data.assign(0);
  }
  SerialMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data()
    , length(0)  {
  (void)_alloc;
      data.assign(0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<uint8_t, 256>  _data_type;
  _data_type data;

   typedef int32_t _length_type;
  _length_type length;





  typedef boost::shared_ptr< ::common_msgs::SerialMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::SerialMsg_<ContainerAllocator> const> ConstPtr;

}; // struct SerialMsg_

typedef ::common_msgs::SerialMsg_<std::allocator<void> > SerialMsg;

typedef boost::shared_ptr< ::common_msgs::SerialMsg > SerialMsgPtr;
typedef boost::shared_ptr< ::common_msgs::SerialMsg const> SerialMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::SerialMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::SerialMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_msgs::SerialMsg_<ContainerAllocator1> & lhs, const ::common_msgs::SerialMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data &&
    lhs.length == rhs.length;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_msgs::SerialMsg_<ContainerAllocator1> & lhs, const ::common_msgs::SerialMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::SerialMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::SerialMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::SerialMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::SerialMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::SerialMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::SerialMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::SerialMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "04e569ccde7b2c8a16c1d0048b38a73e";
  }

  static const char* value(const ::common_msgs::SerialMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x04e569ccde7b2c8aULL;
  static const uint64_t static_value2 = 0x16c1d0048b38a73eULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::SerialMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/SerialMsg";
  }

  static const char* value(const ::common_msgs::SerialMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::SerialMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8[256] data\n"
"int32 length\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::common_msgs::SerialMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::SerialMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
      stream.next(m.length);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SerialMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::SerialMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::SerialMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "length: ";
    Printer<int32_t>::stream(s, indent + "  ", v.length);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_SERIALMSG_H
