// Generated by gencpp from file common_msgs/Trigger.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_TRIGGER_H
#define COMMON_MSGS_MESSAGE_TRIGGER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace common_msgs
{
template <class ContainerAllocator>
struct Trigger_
{
  typedef Trigger_<ContainerAllocator> Type;

  Trigger_()
    : header()
    , trigger(false)  {
    }
  Trigger_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , trigger(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _trigger_type;
  _trigger_type trigger;





  typedef boost::shared_ptr< ::common_msgs::Trigger_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::Trigger_<ContainerAllocator> const> ConstPtr;

}; // struct Trigger_

typedef ::common_msgs::Trigger_<std::allocator<void> > Trigger;

typedef boost::shared_ptr< ::common_msgs::Trigger > TriggerPtr;
typedef boost::shared_ptr< ::common_msgs::Trigger const> TriggerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::Trigger_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::Trigger_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_msgs::Trigger_<ContainerAllocator1> & lhs, const ::common_msgs::Trigger_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.trigger == rhs.trigger;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_msgs::Trigger_<ContainerAllocator1> & lhs, const ::common_msgs::Trigger_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::Trigger_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::Trigger_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::Trigger_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::Trigger_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::Trigger_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::Trigger_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::Trigger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb381b11b4dbec913c041cb0ec39302e";
  }

  static const char* value(const ::common_msgs::Trigger_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb381b11b4dbec91ULL;
  static const uint64_t static_value2 = 0x3c041cb0ec39302eULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::Trigger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/Trigger";
  }

  static const char* value(const ::common_msgs::Trigger_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::Trigger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# trigger signal\n"
"bool trigger\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::common_msgs::Trigger_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::Trigger_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.trigger);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Trigger_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::Trigger_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::Trigger_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "trigger: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trigger);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_TRIGGER_H
