// Generated by gencpp from file common_msgs/VirtualVehicleState.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_VIRTUALVEHICLESTATE_H
#define COMMON_MSGS_MESSAGE_VIRTUALVEHICLESTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <common_msgs/ChassisState.h>
#include <nav_msgs/Odometry.h>

namespace common_msgs
{
template <class ContainerAllocator>
struct VirtualVehicleState_
{
  typedef VirtualVehicleState_<ContainerAllocator> Type;

  VirtualVehicleState_()
    : header()
    , chassis_state()
    , utmpose()
    , distance(0.0)  {
    }
  VirtualVehicleState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , chassis_state(_alloc)
    , utmpose(_alloc)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::common_msgs::ChassisState_<ContainerAllocator>  _chassis_state_type;
  _chassis_state_type chassis_state;

   typedef  ::nav_msgs::Odometry_<ContainerAllocator>  _utmpose_type;
  _utmpose_type utmpose;

   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::common_msgs::VirtualVehicleState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::VirtualVehicleState_<ContainerAllocator> const> ConstPtr;

}; // struct VirtualVehicleState_

typedef ::common_msgs::VirtualVehicleState_<std::allocator<void> > VirtualVehicleState;

typedef boost::shared_ptr< ::common_msgs::VirtualVehicleState > VirtualVehicleStatePtr;
typedef boost::shared_ptr< ::common_msgs::VirtualVehicleState const> VirtualVehicleStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::VirtualVehicleState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::VirtualVehicleState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_msgs::VirtualVehicleState_<ContainerAllocator1> & lhs, const ::common_msgs::VirtualVehicleState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.chassis_state == rhs.chassis_state &&
    lhs.utmpose == rhs.utmpose &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_msgs::VirtualVehicleState_<ContainerAllocator1> & lhs, const ::common_msgs::VirtualVehicleState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::VirtualVehicleState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::VirtualVehicleState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::VirtualVehicleState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::VirtualVehicleState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::VirtualVehicleState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::VirtualVehicleState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::VirtualVehicleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db3fe834d391bbb120083ed33a99aba4";
  }

  static const char* value(const ::common_msgs::VirtualVehicleState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb3fe834d391bbb1ULL;
  static const uint64_t static_value2 = 0x20083ed33a99aba4ULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::VirtualVehicleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/VirtualVehicleState";
  }

  static const char* value(const ::common_msgs::VirtualVehicleState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::VirtualVehicleState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# chassis state\n"
"common_msgs/ChassisState chassis_state\n"
"\n"
"# localization information\n"
"nav_msgs/Odometry utmpose\n"
"\n"
"# distance \n"
"float64 distance\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: common_msgs/ChassisState\n"
"std_msgs/Header header\n"
"\n"
"# real acc pedal value\n"
"uint8 real_acc_pedal\n"
"\n"
"# real brake pedal value\n"
"uint8 real_brake_pedal\n"
"\n"
"# real steering wheel angle\n"
"float64 real_steer_angle_left\n"
"float64 real_steer_angle_right\n"
"\n"
"# vehicle longitudinal acceleration\n"
"float64 vehicle_lon_acceleration\n"
"================================================================================\n"
"MSG: nav_msgs/Odometry\n"
"# This represents an estimate of a position and velocity in free space.  \n"
"# The pose in this message should be specified in the coordinate frame given by header.frame_id.\n"
"# The twist in this message should be specified in the coordinate frame given by the child_frame_id\n"
"Header header\n"
"string child_frame_id\n"
"geometry_msgs/PoseWithCovariance pose\n"
"geometry_msgs/TwistWithCovariance twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistWithCovariance\n"
"# This expresses velocity in free space with uncertainty.\n"
"\n"
"Twist twist\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::common_msgs::VirtualVehicleState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::VirtualVehicleState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.chassis_state);
      stream.next(m.utmpose);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VirtualVehicleState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::VirtualVehicleState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::VirtualVehicleState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "chassis_state: ";
    s << std::endl;
    Printer< ::common_msgs::ChassisState_<ContainerAllocator> >::stream(s, indent + "  ", v.chassis_state);
    s << indent << "utmpose: ";
    s << std::endl;
    Printer< ::nav_msgs::Odometry_<ContainerAllocator> >::stream(s, indent + "  ", v.utmpose);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_VIRTUALVEHICLESTATE_H
