(cl:defpackage common_msgs-msg
  (:use )
  (:export
   "<CHASSISCONTROL>"
   "CHASSISCONTROL"
   "<CHASSISSTATE>"
   "CHASSISSTATE"
   "<CONTROLCOMMAND>"
   "CONTROLCOMMAND"
   "<CONTROLCOMMANDSTAMPED>"
   "CONTROLCOMMANDSTAMPED"
   "<CONTROLSTATE>"
   "CONTROLSTATE"
   "<GPSINFO>"
   "GPSINFO"
   "<MAGNETICSIGNAL>"
   "MAGNETICSIGNAL"
   "<REMOTECONTROL>"
   "REMOTECONTROL"
   "<SERIALMSG>"
   "SERIALMSG"
   "<TRIGGER>"
   "TRIGGER"
   "<VIRTUALVEHICLESTATE>"
   "VIRTUALVEHICLESTATE"
  ))

