# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from common_msgs/ChassisControl.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class ChassisControl(genpy.Message):
  _md5sum = "f4a7a2ade840279ee54283672cf94d29"
  _type = "common_msgs/ChassisControl"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

float64 acc_request
int32 acc_control_mode
int32 acc_loop_number
int32 acc_pedal_open_request
int32 brk_pedal_open_request

int32 steer_enable
float64 steer_angle_velocity
float64 steer_angle

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','acc_request','acc_control_mode','acc_loop_number','acc_pedal_open_request','brk_pedal_open_request','steer_enable','steer_angle_velocity','steer_angle']
  _slot_types = ['std_msgs/Header','float64','int32','int32','int32','int32','int32','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,acc_request,acc_control_mode,acc_loop_number,acc_pedal_open_request,brk_pedal_open_request,steer_enable,steer_angle_velocity,steer_angle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ChassisControl, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.acc_request is None:
        self.acc_request = 0.
      if self.acc_control_mode is None:
        self.acc_control_mode = 0
      if self.acc_loop_number is None:
        self.acc_loop_number = 0
      if self.acc_pedal_open_request is None:
        self.acc_pedal_open_request = 0
      if self.brk_pedal_open_request is None:
        self.brk_pedal_open_request = 0
      if self.steer_enable is None:
        self.steer_enable = 0
      if self.steer_angle_velocity is None:
        self.steer_angle_velocity = 0.
      if self.steer_angle is None:
        self.steer_angle = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.acc_request = 0.
      self.acc_control_mode = 0
      self.acc_loop_number = 0
      self.acc_pedal_open_request = 0
      self.brk_pedal_open_request = 0
      self.steer_enable = 0
      self.steer_angle_velocity = 0.
      self.steer_angle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_d5i2d().pack(_x.acc_request, _x.acc_control_mode, _x.acc_loop_number, _x.acc_pedal_open_request, _x.brk_pedal_open_request, _x.steer_enable, _x.steer_angle_velocity, _x.steer_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 44
      (_x.acc_request, _x.acc_control_mode, _x.acc_loop_number, _x.acc_pedal_open_request, _x.brk_pedal_open_request, _x.steer_enable, _x.steer_angle_velocity, _x.steer_angle,) = _get_struct_d5i2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_d5i2d().pack(_x.acc_request, _x.acc_control_mode, _x.acc_loop_number, _x.acc_pedal_open_request, _x.brk_pedal_open_request, _x.steer_enable, _x.steer_angle_velocity, _x.steer_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 44
      (_x.acc_request, _x.acc_control_mode, _x.acc_loop_number, _x.acc_pedal_open_request, _x.brk_pedal_open_request, _x.steer_enable, _x.steer_angle_velocity, _x.steer_angle,) = _get_struct_d5i2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_d5i2d = None
def _get_struct_d5i2d():
    global _struct_d5i2d
    if _struct_d5i2d is None:
        _struct_d5i2d = struct.Struct("<d5i2d")
    return _struct_d5i2d
