# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from common_msgs/VirtualVehicleState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import common_msgs.msg
import geometry_msgs.msg
import nav_msgs.msg
import std_msgs.msg

class VirtualVehicleState(genpy.Message):
  _md5sum = "db3fe834d391bbb120083ed33a99aba4"
  _type = "common_msgs/VirtualVehicleState"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

# chassis state
common_msgs/ChassisState chassis_state

# localization information
nav_msgs/Odometry utmpose

# distance 
float64 distance
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: common_msgs/ChassisState
std_msgs/Header header

# real acc pedal value
uint8 real_acc_pedal

# real brake pedal value
uint8 real_brake_pedal

# real steering wheel angle
float64 real_steer_angle_left
float64 real_steer_angle_right

# vehicle longitudinal acceleration
float64 vehicle_lon_acceleration
================================================================================
MSG: nav_msgs/Odometry
# This represents an estimate of a position and velocity in free space.  
# The pose in this message should be specified in the coordinate frame given by header.frame_id.
# The twist in this message should be specified in the coordinate frame given by the child_frame_id
Header header
string child_frame_id
geometry_msgs/PoseWithCovariance pose
geometry_msgs/TwistWithCovariance twist

================================================================================
MSG: geometry_msgs/PoseWithCovariance
# This represents a pose in free space with uncertainty.

Pose pose

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/TwistWithCovariance
# This expresses velocity in free space with uncertainty.

Twist twist

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','chassis_state','utmpose','distance']
  _slot_types = ['std_msgs/Header','common_msgs/ChassisState','nav_msgs/Odometry','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,chassis_state,utmpose,distance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VirtualVehicleState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.chassis_state is None:
        self.chassis_state = common_msgs.msg.ChassisState()
      if self.utmpose is None:
        self.utmpose = nav_msgs.msg.Odometry()
      if self.distance is None:
        self.distance = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.chassis_state = common_msgs.msg.ChassisState()
      self.utmpose = nav_msgs.msg.Odometry()
      self.distance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.chassis_state.header.seq, _x.chassis_state.header.stamp.secs, _x.chassis_state.header.stamp.nsecs))
      _x = self.chassis_state.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B3d3I().pack(_x.chassis_state.real_acc_pedal, _x.chassis_state.real_brake_pedal, _x.chassis_state.real_steer_angle_left, _x.chassis_state.real_steer_angle_right, _x.chassis_state.vehicle_lon_acceleration, _x.utmpose.header.seq, _x.utmpose.header.stamp.secs, _x.utmpose.header.stamp.nsecs))
      _x = self.utmpose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.utmpose.child_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.utmpose.pose.pose.position.x, _x.utmpose.pose.pose.position.y, _x.utmpose.pose.pose.position.z, _x.utmpose.pose.pose.orientation.x, _x.utmpose.pose.pose.orientation.y, _x.utmpose.pose.pose.orientation.z, _x.utmpose.pose.pose.orientation.w))
      buff.write(_get_struct_36d().pack(*self.utmpose.pose.covariance))
      _x = self
      buff.write(_get_struct_6d().pack(_x.utmpose.twist.twist.linear.x, _x.utmpose.twist.twist.linear.y, _x.utmpose.twist.twist.linear.z, _x.utmpose.twist.twist.angular.x, _x.utmpose.twist.twist.angular.y, _x.utmpose.twist.twist.angular.z))
      buff.write(_get_struct_36d().pack(*self.utmpose.twist.covariance))
      _x = self.distance
      buff.write(_get_struct_d().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.chassis_state is None:
        self.chassis_state = common_msgs.msg.ChassisState()
      if self.utmpose is None:
        self.utmpose = nav_msgs.msg.Odometry()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.chassis_state.header.seq, _x.chassis_state.header.stamp.secs, _x.chassis_state.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.chassis_state.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.chassis_state.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 38
      (_x.chassis_state.real_acc_pedal, _x.chassis_state.real_brake_pedal, _x.chassis_state.real_steer_angle_left, _x.chassis_state.real_steer_angle_right, _x.chassis_state.vehicle_lon_acceleration, _x.utmpose.header.seq, _x.utmpose.header.stamp.secs, _x.utmpose.header.stamp.nsecs,) = _get_struct_2B3d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.utmpose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.utmpose.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.utmpose.child_frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.utmpose.child_frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.utmpose.pose.pose.position.x, _x.utmpose.pose.pose.position.y, _x.utmpose.pose.pose.position.z, _x.utmpose.pose.pose.orientation.x, _x.utmpose.pose.pose.orientation.y, _x.utmpose.pose.pose.orientation.z, _x.utmpose.pose.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 288
      self.utmpose.pose.covariance = _get_struct_36d().unpack(str[start:end])
      _x = self
      start = end
      end += 48
      (_x.utmpose.twist.twist.linear.x, _x.utmpose.twist.twist.linear.y, _x.utmpose.twist.twist.linear.z, _x.utmpose.twist.twist.angular.x, _x.utmpose.twist.twist.angular.y, _x.utmpose.twist.twist.angular.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 288
      self.utmpose.twist.covariance = _get_struct_36d().unpack(str[start:end])
      start = end
      end += 8
      (self.distance,) = _get_struct_d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.chassis_state.header.seq, _x.chassis_state.header.stamp.secs, _x.chassis_state.header.stamp.nsecs))
      _x = self.chassis_state.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B3d3I().pack(_x.chassis_state.real_acc_pedal, _x.chassis_state.real_brake_pedal, _x.chassis_state.real_steer_angle_left, _x.chassis_state.real_steer_angle_right, _x.chassis_state.vehicle_lon_acceleration, _x.utmpose.header.seq, _x.utmpose.header.stamp.secs, _x.utmpose.header.stamp.nsecs))
      _x = self.utmpose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.utmpose.child_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.utmpose.pose.pose.position.x, _x.utmpose.pose.pose.position.y, _x.utmpose.pose.pose.position.z, _x.utmpose.pose.pose.orientation.x, _x.utmpose.pose.pose.orientation.y, _x.utmpose.pose.pose.orientation.z, _x.utmpose.pose.pose.orientation.w))
      buff.write(self.utmpose.pose.covariance.tostring())
      _x = self
      buff.write(_get_struct_6d().pack(_x.utmpose.twist.twist.linear.x, _x.utmpose.twist.twist.linear.y, _x.utmpose.twist.twist.linear.z, _x.utmpose.twist.twist.angular.x, _x.utmpose.twist.twist.angular.y, _x.utmpose.twist.twist.angular.z))
      buff.write(self.utmpose.twist.covariance.tostring())
      _x = self.distance
      buff.write(_get_struct_d().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.chassis_state is None:
        self.chassis_state = common_msgs.msg.ChassisState()
      if self.utmpose is None:
        self.utmpose = nav_msgs.msg.Odometry()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.chassis_state.header.seq, _x.chassis_state.header.stamp.secs, _x.chassis_state.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.chassis_state.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.chassis_state.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 38
      (_x.chassis_state.real_acc_pedal, _x.chassis_state.real_brake_pedal, _x.chassis_state.real_steer_angle_left, _x.chassis_state.real_steer_angle_right, _x.chassis_state.vehicle_lon_acceleration, _x.utmpose.header.seq, _x.utmpose.header.stamp.secs, _x.utmpose.header.stamp.nsecs,) = _get_struct_2B3d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.utmpose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.utmpose.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.utmpose.child_frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.utmpose.child_frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.utmpose.pose.pose.position.x, _x.utmpose.pose.pose.position.y, _x.utmpose.pose.pose.position.z, _x.utmpose.pose.pose.orientation.x, _x.utmpose.pose.pose.orientation.y, _x.utmpose.pose.pose.orientation.z, _x.utmpose.pose.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 288
      self.utmpose.pose.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 48
      (_x.utmpose.twist.twist.linear.x, _x.utmpose.twist.twist.linear.y, _x.utmpose.twist.twist.linear.z, _x.utmpose.twist.twist.angular.x, _x.utmpose.twist.twist.angular.y, _x.utmpose.twist.twist.angular.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 288
      self.utmpose.twist.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      start = end
      end += 8
      (self.distance,) = _get_struct_d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B3d3I = None
def _get_struct_2B3d3I():
    global _struct_2B3d3I
    if _struct_2B3d3I is None:
        _struct_2B3d3I = struct.Struct("<2B3d3I")
    return _struct_2B3d3I
_struct_36d = None
def _get_struct_36d():
    global _struct_36d
    if _struct_36d is None:
        _struct_36d = struct.Struct("<36d")
    return _struct_36d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
