# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from simple_lane_detection/object.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class object(genpy.Message):
  _md5sum = "10f6e7b97734158810c589b4cdb3ff51"
  _type = "simple_lane_detection/object"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

float32 left_cx_down 
float32 left_cx_upper
float32 left_cy_down 
float32 letf_cy_upper

float32 mid_cx_down
float32 mid_cx_upper 
float32 mid_cy_down 
float32 mid_cy_upper 

float32 rig_cx_down 
float32 rig_cx_upper 
float32 rig_cy_down 
float32 rig_cy_upper 
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','left_cx_down','left_cx_upper','left_cy_down','letf_cy_upper','mid_cx_down','mid_cx_upper','mid_cy_down','mid_cy_upper','rig_cx_down','rig_cx_upper','rig_cy_down','rig_cy_upper']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,left_cx_down,left_cx_upper,left_cy_down,letf_cy_upper,mid_cx_down,mid_cx_upper,mid_cy_down,mid_cy_upper,rig_cx_down,rig_cx_upper,rig_cy_down,rig_cy_upper

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(object, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left_cx_down is None:
        self.left_cx_down = 0.
      if self.left_cx_upper is None:
        self.left_cx_upper = 0.
      if self.left_cy_down is None:
        self.left_cy_down = 0.
      if self.letf_cy_upper is None:
        self.letf_cy_upper = 0.
      if self.mid_cx_down is None:
        self.mid_cx_down = 0.
      if self.mid_cx_upper is None:
        self.mid_cx_upper = 0.
      if self.mid_cy_down is None:
        self.mid_cy_down = 0.
      if self.mid_cy_upper is None:
        self.mid_cy_upper = 0.
      if self.rig_cx_down is None:
        self.rig_cx_down = 0.
      if self.rig_cx_upper is None:
        self.rig_cx_upper = 0.
      if self.rig_cy_down is None:
        self.rig_cy_down = 0.
      if self.rig_cy_upper is None:
        self.rig_cy_upper = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.left_cx_down = 0.
      self.left_cx_upper = 0.
      self.left_cy_down = 0.
      self.letf_cy_upper = 0.
      self.mid_cx_down = 0.
      self.mid_cx_upper = 0.
      self.mid_cy_down = 0.
      self.mid_cy_upper = 0.
      self.rig_cx_down = 0.
      self.rig_cx_upper = 0.
      self.rig_cy_down = 0.
      self.rig_cy_upper = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_12f().pack(_x.left_cx_down, _x.left_cx_upper, _x.left_cy_down, _x.letf_cy_upper, _x.mid_cx_down, _x.mid_cx_upper, _x.mid_cy_down, _x.mid_cy_upper, _x.rig_cx_down, _x.rig_cx_upper, _x.rig_cy_down, _x.rig_cy_upper))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.left_cx_down, _x.left_cx_upper, _x.left_cy_down, _x.letf_cy_upper, _x.mid_cx_down, _x.mid_cx_upper, _x.mid_cy_down, _x.mid_cy_upper, _x.rig_cx_down, _x.rig_cx_upper, _x.rig_cy_down, _x.rig_cy_upper,) = _get_struct_12f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_12f().pack(_x.left_cx_down, _x.left_cx_upper, _x.left_cy_down, _x.letf_cy_upper, _x.mid_cx_down, _x.mid_cx_upper, _x.mid_cy_down, _x.mid_cy_upper, _x.rig_cx_down, _x.rig_cx_upper, _x.rig_cy_down, _x.rig_cy_upper))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.left_cx_down, _x.left_cx_upper, _x.left_cy_down, _x.letf_cy_upper, _x.mid_cx_down, _x.mid_cx_upper, _x.mid_cy_down, _x.mid_cy_upper, _x.rig_cx_down, _x.rig_cx_upper, _x.rig_cy_down, _x.rig_cy_upper,) = _get_struct_12f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12f = None
def _get_struct_12f():
    global _struct_12f
    if _struct_12f is None:
        _struct_12f = struct.Struct("<12f")
    return _struct_12f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
