chassis_control_topic_name: /control_cmd

chassis_state_topic_name: /chassis_state

cansend_topic_name: /sent_messages_can0

cansend_can1_topic_name: /sent_messages_can1

node_rate: 25   # [Herz]

cansend_para:
  send_mode: 1 # 0 for test and 1 for autonomous driving
  test_steer_angle: 0
  test_motor_input: 0.1 # [-1,1], test_motor_rpm = test_motor_input * max_motor_rpm
  motor_max_rpm: 1500
  motor_dead_input: 0.4
  steer_max_angle: 45
  steer_dead_input: 0.2
  motor_manual_rpm: 1500
  motor_auto_rpm: 1000
  steer_offset_left: 10000
  steer_offset_right: -1090000
  motor_direction: 1
  vehicle_B: 1.7
  vehicle_L: 3.03

angle_error_pid:
  kp: 0.04
  ki: 0.0
  kd: 0.0


  